const test=require('node:test');const assert=require('node:assert/strict');const fs=require('fs');const os=require('os');const path=require('path');
const vault=require('../server-plugin/lib/vault');const search=require('../server-plugin/lib/search');
async function temp(){return fs.promises.mkdtemp(path.join(os.tmpdir(),'ignis-api-'));}
test('normalize path blocks traversal and absolute paths',()=>{assert.throws(()=>vault.normalizeRelativePath('../x'));assert.throws(()=>vault.normalizeRelativePath('/etc/passwd'));assert.equal(vault.normalizeRelativePath('a/../b'),'b');});
test('write/list/read/move/copy/trash lifecycle',async()=>{const root=await temp();await vault.writeFile(root,'folder/a.md','hello');assert.deepEqual(await vault.listDirectory(root,'folder'),['a.md']);assert.equal((await vault.readFile(root,'folder/a.md')).toString(),'hello');assert.equal(await vault.copyFile(root,'folder/a.md','copies/'),'copies/a.md');assert.equal(await vault.moveFile(root,'folder/a.md','renamed.md'),'renamed.md');assert.equal((await vault.readFile(root,'renamed.md')).toString(),'hello');const del=await vault.deleteFile(root,'renamed.md');assert.match(del.trashedTo,/^\.trash\//);});
test('move refuses overwrite unless explicitly allowed',async()=>{const root=await temp();await vault.writeFile(root,'a.md','a');await vault.writeFile(root,'b.md','b');await assert.rejects(()=>vault.moveFile(root,'a.md','b.md'),(e)=>e.statusCode===409);await vault.moveFile(root,'a.md','b.md',{allowOverwrite:true});assert.equal((await vault.readFile(root,'b.md')).toString(),'a');});
test('simple search returns upstream-shaped filename and match source',async()=>{const root=await temp();await vault.writeFile(root,'Needle.md','hello needle world');const r=await search.simpleSearch(root,'needle',10);assert.equal(r[0].filename,'Needle.md');assert.ok(r[0].matches.some((m)=>m.match.source==='content'));assert.ok(r[0].matches.some((m)=>m.match.source==='filename'));});
test('tags include parent hierarchy',async()=>{const root=await temp();await vault.writeFile(root,'a.md','---\ntags: [project/sub]\n---\n#inline/child\n');const tags=await search.tagCounts(root);const map=Object.fromEntries(tags.map((t)=>[t.name,t.count]));assert.equal(map.project,1);assert.equal(map['project/sub'],1);assert.equal(map.inline,1);assert.equal(map['inline/child'],1);});
test('metadata resolves links, backlinks, and unresolved links',async()=>{const root=await temp();await vault.writeFile(root,'a.md','[[b]] [[missing]]');await vault.writeFile(root,'b.md','# B');const index=await search.buildFileIndex(root);const backs=await search.buildBacklinks(root,index);const a=await search.metadataForFile(root,'a.md',{index,backlinkIndex:backs});const b=await search.metadataForFile(root,'b.md',{index,backlinkIndex:backs});assert.deepEqual(a.links,['b.md']);assert.deepEqual(a.unresolvedLinks,['missing']);assert.deepEqual(b.backlinks,['a.md']);});
test('JsonLogic query supports var, in, glob, regexp, and returns filename/result',async()=>{const root=await temp();await vault.writeFile(root,'notes/a.md','---\nstatus: done\n---\nhello');await vault.writeFile(root,'notes/b.md','---\nstatus: todo\n---\nworld');let r=await search.structuredSearch(root,{'===':[{'var':'frontmatter.status'},'done']});assert.deepEqual(r.map((x)=>x.filename),['notes/a.md']);r=await search.structuredSearch(root,{glob:['notes/*.md',{'var':'path'}]});assert.equal(r.length,2);r=await search.structuredSearch(root,{regexp:['hell',{'var':'content'}]});assert.deepEqual(r.map((x)=>x.filename),['notes/a.md']);});
